<?php

namespace Lddt\MainBundle\Repository;

/**
 * PicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicRepository extends \Doctrine\ORM\EntityRepository
{
}
