lddt_main_homepage:
    path:     /
    defaults: { _controller: LddtMainBundle:Default:index }

lddt_main_show:
    path:     /show/{id}
    defaults: { _controller: LddtMainBundle:Default:show }
    requirements:
         id: \d+

lddt_main_create:
    path:     /create
    defaults: { _controller: LddtMainBundle:Default:create }

lddt_main_delete:
    path:     /delete/{id}
    defaults: { _controller: LddtMainBundle:Default:delete, id:null }
    requirements:
         id: \d+

lddt_main_edit:
    path:     /edit/{id}
    defaults: { _controller: LddtMainBundle:Default:edit }
    requirements:
         id: \d+

lddt_main_list_by_cat:
    path:     /category/{id}
    defaults: { _controller: LddtMainBundle:Default:listDrawsByCat }
    requirements:
         id: \d+

lddt_main_list_by_color:
    path:     /color/{id}
    defaults: { _controller: LddtMainBundle:Default:listDrawsByColor }
    requirements:
         id: \d+

lddt_main_list_by_tag:
    path:     /tag/{id}
    defaults: { _controller: LddtMainBundle:Default:listDrawsByTag }
    requirements:
         id: \d+